# Generated by Django 4.1.7 on 2023-04-14 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('Information Technology', 'Information Technology'), ('Business Management', 'Business Management'), ('Sales Executive', 'Sales Executive'), ('Accounting', 'Accounting'), ('Health & Science', ' Health & Science'), ('Architecture', 'Architecture'), ('Education Careers', 'Education Careers')], default='IT field', max_length=200)),
                ('role', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('salary', models.CharField(max_length=150)),
                ('duration', models.CharField(choices=[('Full-time', 'Full-time'), ('Half-time', 'Half-time')], max_length=150)),
                ('job_description', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('call', models.IntegerField()),
                ('Hired', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('qualification', models.CharField(choices=[('Master', 'Master'), ('Btech', 'Btech'), ('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Other', 'Other')], default='qualification', max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('cgpa', models.IntegerField()),
                ('experience', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='resume/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='student.jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('qualification', models.CharField(choices=[('Master', 'Master'), ('Btech', 'Btech'), ('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Other', 'Other')], default='qualification', max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('cgpa', models.IntegerField()),
                ('experience', models.CharField(max_length=200)),
                ('skills', models.TextField(default='Hard skills required.....Eg:Programming languages like Java,C++ etc', max_length=200)),
                ('resume', models.FileField(blank=True, max_length=200, upload_to='resume/')),
                ('profile', models.ImageField(blank=True, upload_to='image/')),
                ('complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
