# Generated by Django 4.2 on 2023-04-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Count',
        ),
    ]
