# Generated by Django 4.2 on 2023-04-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=1000)),
                ('link', models.URLField()),
            ],
        ),
    ]
