# Generated by Django 4.2 on 2023-04-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.URLField(),
        ),
    ]
